### ISSUE TITLE
Bug fix roadmap

### ISSUE THREAD

**Issue by davibrandao18** [codando-community/coderslab#101]
- [ ] Correção para exibição do nome do Roadmap em detail.
- [ ] Exibição correta do componente de tasks.
- [ ] Correções de status no componente accordion.
- [ ] Limpeza de console logs no escopo de roadmap.
